// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace cosmos.base.tendermint.v1beta1 {

    // GetValidatorSetByHeightRequest is the request type for the Query/GetValidatorSetByHeight RPC method.
    export interface GetValidatorSetByHeightRequest {
        height?: number;
        // pagination defines an pagination for the request.
        pagination?: cosmos.base.query.v1beta1.PageRequest;
    }

    // GetValidatorSetByHeightResponse is the response type for the Query/GetValidatorSetByHeight RPC method.
    export interface GetValidatorSetByHeightResponse {
        block_height?: number;
        validators?: Array<Validator>;
        // pagination defines an pagination for the response.
        pagination?: cosmos.base.query.v1beta1.PageResponse;
    }

    // GetLatestValidatorSetRequest is the request type for the Query/GetValidatorSetByHeight RPC method.
    export interface GetLatestValidatorSetRequest {
        // pagination defines an pagination for the request.
        pagination?: cosmos.base.query.v1beta1.PageRequest;
    }

    // GetLatestValidatorSetResponse is the response type for the Query/GetValidatorSetByHeight RPC method.
    export interface GetLatestValidatorSetResponse {
        block_height?: number;
        validators?: Array<Validator>;
        // pagination defines an pagination for the response.
        pagination?: cosmos.base.query.v1beta1.PageResponse;
    }

    // Validator is the type for the validator-set.
    export interface Validator {
        address?: string;
        pub_key?: google.protobuf.Any;
        voting_power?: number;
        proposer_priority?: number;
    }

    // GetBlockByHeightRequest is the request type for the Query/GetBlockByHeight RPC method.
    export interface GetBlockByHeightRequest {
        height?: number;
    }

    // GetBlockByHeightResponse is the response type for the Query/GetBlockByHeight RPC method.
    export interface GetBlockByHeightResponse {
        block_id?: tendermint.types.BlockID;
        block?: tendermint.types.Block;
    }

    // GetLatestBlockRequest is the request type for the Query/GetLatestBlock RPC method.
    export interface GetLatestBlockRequest {
    }

    // GetLatestBlockResponse is the response type for the Query/GetLatestBlock RPC method.
    export interface GetLatestBlockResponse {
        block_id?: tendermint.types.BlockID;
        block?: tendermint.types.Block;
    }

    // GetSyncingRequest is the request type for the Query/GetSyncing RPC method.
    export interface GetSyncingRequest {
    }

    // GetSyncingResponse is the response type for the Query/GetSyncing RPC method.
    export interface GetSyncingResponse {
        syncing?: boolean;
    }

    // GetNodeInfoRequest is the request type for the Query/GetNodeInfo RPC method.
    export interface GetNodeInfoRequest {
    }

    // GetNodeInfoResponse is the response type for the Query/GetNodeInfo RPC method.
    export interface GetNodeInfoResponse {
        node_info?: tendermint.p2p.NodeInfo;
        application_version?: VersionInfo;
    }

    // VersionInfo is the type for the GetNodeInfoResponse message.
    export interface VersionInfo {
        name?: string;
        app_name?: string;
        version?: string;
        git_commit?: string;
        build_tags?: string;
        go_version?: string;
        build_deps?: Array<Module>;
        // Since: cosmos-sdk 0.43
        cosmos_sdk_version?: string;
    }

    // Module is the type for VersionInfo
    export interface Module {
        // module path
        path?: string;
        // module version
        version?: string;
        // checksum
        sum?: string;
    }

    export interface ServiceService {
        GetNodeInfo: (r:GetNodeInfoRequest) => GetNodeInfoResponse;
        GetSyncing: (r:GetSyncingRequest) => GetSyncingResponse;
        GetLatestBlock: (r:GetLatestBlockRequest) => GetLatestBlockResponse;
        GetBlockByHeight: (r:GetBlockByHeightRequest) => GetBlockByHeightResponse;
        GetLatestValidatorSet: (r:GetLatestValidatorSetRequest) => GetLatestValidatorSetResponse;
        GetValidatorSetByHeight: (r:GetValidatorSetByHeightRequest) => GetValidatorSetByHeightResponse;
    }
}

