// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace google.api {

    // `Service` is the root object of Google service configuration schema. It
    // describes basic information about a service, such as the name and the
    // title, and delegates other aspects to sub-sections. Each sub-section is
    // either a proto message or a repeated proto message that configures a
    // specific aspect, such as auth. See each proto message definition for details.
    //
    // Example:
    //
    //     type: google.api.Service
    //     name: calendar.googleapis.com
    //     title: Google Calendar API
    //     apis:
    //     - name: google.calendar.v3.Calendar
    //     authentication:
    //       providers:
    //       - id: google_calendar_auth
    //         jwks_uri: https://www.googleapis.com/oauth2/v1/certs
    //         issuer: https://securetoken.google.com
    //       rules:
    //       - selector: "*"
    //         requirements:
    //           provider_id: google_calendar_auth
    export interface Service {
        // The service name, which is a DNS-like logical identifier for the
        // service, such as `calendar.googleapis.com`. The service name
        // typically goes through DNS verification to make sure the owner
        // of the service also owns the DNS name.
        name?: string;
        // The product title for this service.
        title?: string;
        // The Google project that owns this service.
        producer_project_id?: string;
        // A unique ID for a specific instance of this message, typically assigned
        // by the client for tracking purpose. Must be no longer than 63 characters
        // and only lower case letters, digits, '.', '_' and '-' are allowed. If
        // empty, the server may choose to generate one instead.
        id?: string;
        // A list of API interfaces exported by this service. Only the `name` field
        // of the [google.protobuf.Api][google.protobuf.Api] needs to be provided by the configuration
        // author, as the remaining fields will be derived from the IDL during the
        // normalization process. It is an error to specify an API interface here
        // which cannot be resolved against the associated IDL files.
        apis?: Array<google.protobuf.Api>;
        // A list of all proto message types included in this API service.
        // Types referenced directly or indirectly by the `apis` are
        // automatically included.  Messages which are not referenced but
        // shall be included, such as types used by the `google.protobuf.Any` type,
        // should be listed here by name. Example:
        //
        //     types:
        //     - name: google.protobuf.Int32
        types?: Array<google.protobuf.Type>;
        // A list of all enum types included in this API service.  Enums
        // referenced directly or indirectly by the `apis` are automatically
        // included.  Enums which are not referenced but shall be included
        // should be listed here by name. Example:
        //
        //     enums:
        //     - name: google.someapi.v1.SomeEnum
        enums?: Array<google.protobuf.Enum>;
        // Additional API documentation.
        documentation?: Documentation;
        // API backend configuration.
        backend?: Backend;
        // HTTP configuration.
        http?: Http;
        // Quota configuration.
        quota?: Quota;
        // Auth configuration.
        authentication?: Authentication;
        // Context configuration.
        context?: Context;
        // Configuration controlling usage of this service.
        usage?: Usage;
        // Configuration for network endpoints.  If this is empty, then an endpoint
        // with the same name as the service is automatically generated to service all
        // defined APIs.
        endpoints?: Array<Endpoint>;
        // Configuration for the service control plane.
        control?: Control;
        // Defines the logs used by this service.
        logs?: Array<LogDescriptor>;
        // Defines the metrics used by this service.
        metrics?: Array<MetricDescriptor>;
        // Defines the monitored resources used by this service. This is required
        // by the [Service.monitoring][google.api.Service.monitoring] and [Service.logging][google.api.Service.logging] configurations.
        monitored_resources?: Array<MonitoredResourceDescriptor>;
        // Billing configuration.
        billing?: Billing;
        // Logging configuration.
        logging?: Logging;
        // Monitoring configuration.
        monitoring?: Monitoring;
        // System parameter configuration.
        system_parameters?: SystemParameters;
        // Output only. The source information for this configuration if available.
        source_info?: SourceInfo;
        // Obsolete. Do not use.
        //
        // This field has no semantic meaning. The service config compiler always
        // sets this field to `3`.
        config_version?: google.protobuf.UInt32Value;
    }

}

