// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace google.api {

    export enum LabelDescriptor_ValueType {
        STRING = "STRING",
        BOOL = "BOOL",
        INT64 = "INT64",
    }
    // A description of a label.
    export interface LabelDescriptor {
        // The label key.
        key?: string;
        // The type of data that can be assigned to the label.
        value_type?: LabelDescriptor_ValueType;
        // A human-readable description for the label.
        description?: string;
    }

}

