// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace google.api {

    export enum LaunchStage {
        LAUNCH_STAGE_UNSPECIFIED = "LAUNCH_STAGE_UNSPECIFIED",
        UNIMPLEMENTED = "UNIMPLEMENTED",
        PRELAUNCH = "PRELAUNCH",
        EARLY_ACCESS = "EARLY_ACCESS",
        ALPHA = "ALPHA",
        BETA = "BETA",
        GA = "GA",
        DEPRECATED = "DEPRECATED",
    }
}

