// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace google.api {

    // Selects and configures the service controller used by the service.  The
    // service controller handles features like abuse, quota, billing, logging,
    // monitoring, etc.
    export interface Control {
        // The service control environment to use. If empty, no control plane
        // feature (like quota and billing) will be enabled.
        environment?: string;
    }

}

