// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace cosmos.evidence.v1beta1 {

    // QueryEvidenceRequest is the request type for the Query/Evidence RPC method.
    export interface QueryEvidenceRequest {
        // evidence_hash defines the hash of the requested evidence.
        evidence_hash?: Uint8Array;
    }

    // QueryEvidenceResponse is the response type for the Query/Evidence RPC method.
    export interface QueryEvidenceResponse {
        // evidence returns the requested evidence.
        evidence?: google.protobuf.Any;
    }

    // QueryEvidenceRequest is the request type for the Query/AllEvidence RPC
    // method.
    export interface QueryAllEvidenceRequest {
        // pagination defines an optional pagination for the request.
        pagination?: cosmos.base.query.v1beta1.PageRequest;
    }

    // QueryAllEvidenceResponse is the response type for the Query/AllEvidence RPC
    // method.
    export interface QueryAllEvidenceResponse {
        // evidence returns all evidences.
        evidence?: Array<google.protobuf.Any>;
        // pagination defines the pagination in the response.
        pagination?: cosmos.base.query.v1beta1.PageResponse;
    }

    export interface QueryService {
        Evidence: (r:QueryEvidenceRequest) => QueryEvidenceResponse;
        AllEvidence: (r:QueryAllEvidenceRequest) => QueryAllEvidenceResponse;
    }
}

