// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace cosmos.evidence.v1beta1 {

    // Equivocation implements the Evidence interface and defines evidence of double
    // signing misbehavior.
    export interface Equivocation {
        height?: number;
        time?: google.protobuf.Timestamp;
        power?: number;
        consensus_address?: string;
    }

}

