// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace osmosis.poolincentives.v1beta1 {

    export interface Params {
        // minted_denom is the denomination of the coin expected to be minted by the
        // minting module. Pool-incentives module doesn’t actually mint the coin
        // itself, but rather manages the distribution of coins that matches the
        // defined minted_denom.
        minted_denom?: string;
    }

    export interface LockableDurationsInfo {
        lockable_durations?: Array<google.protobuf.Duration>;
    }

    export interface DistrInfo {
        total_weight?: string;
        records?: Array<DistrRecord>;
    }

    export interface DistrRecord {
        gauge_id?: number;
        weight?: string;
    }

}

