// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace cosmos.crypto.keyring.v1 {

    // Item is a keyring item stored in a keyring backend.
    // Local item
    export interface Record_Local {
        priv_key?: google.protobuf.Any;
        priv_key_type?: string;
    }

    // Ledger item
    export interface Record_Ledger {
        path?: cosmos.crypto.hd.v1.BIP44Params;
    }

    // Multi item
    export interface Record_Multi {
    }

    // Offline item
    export interface Record_Offline {
    }

    // Record is used for representing a key in the keyring.
    export interface Record {
        // name represents a name of Record
        name?: string;
        // pub_key represents a public key in any format
        pub_key?: google.protobuf.Any;
        // local stores the public information about a locally stored key
        local?: Record_Local;
        // ledger stores the public information about a Ledger key
        ledger?: Record_Ledger;
        // Multi does not store any information.
        multi?: Record_Multi;
        // Offline does not store any information.
        offline?: Record_Offline;
    }

}

