// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace osmosis.superfluid {

    // Params holds parameters for the superfluid module
    export interface Params {
        // the risk_factor is to be cut on OSMO equivalent value of lp tokens for
        // superfluid staking, default: 5%
        minimum_risk_factor?: string;
    }

}

