// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace cosmos.params.v1beta1 {

    // ParameterChangeProposal defines a proposal to change one or more parameters.
    export interface ParameterChangeProposal {
        title?: string;
        description?: string;
        changes?: Array<ParamChange>;
    }

    // ParamChange defines an individual parameter change, for use in
    // ParameterChangeProposal.
    export interface ParamChange {
        subspace?: string;
        key?: string;
        value?: string;
    }

}

