// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace cosmos.slashing.v1beta1 {

    // QueryParamsRequest is the request type for the Query/Params RPC method
    export interface QueryParamsRequest {
    }

    // QueryParamsResponse is the response type for the Query/Params RPC method
    export interface QueryParamsResponse {
        params?: Params;
    }

    // QuerySigningInfoRequest is the request type for the Query/SigningInfo RPC
    // method
    export interface QuerySigningInfoRequest {
        // cons_address is the address to query signing info of
        cons_address?: string;
    }

    // QuerySigningInfoResponse is the response type for the Query/SigningInfo RPC
    // method
    export interface QuerySigningInfoResponse {
        // val_signing_info is the signing info of requested val cons address
        val_signing_info?: ValidatorSigningInfo;
    }

    // QuerySigningInfosRequest is the request type for the Query/SigningInfos RPC
    // method
    export interface QuerySigningInfosRequest {
        pagination?: cosmos.base.query.v1beta1.PageRequest;
    }

    // QuerySigningInfosResponse is the response type for the Query/SigningInfos RPC
    // method
    export interface QuerySigningInfosResponse {
        // info is the signing info of all validators
        info?: Array<ValidatorSigningInfo>;
        pagination?: cosmos.base.query.v1beta1.PageResponse;
    }

    export interface QueryService {
        Params: (r:QueryParamsRequest) => QueryParamsResponse;
        SigningInfo: (r:QuerySigningInfoRequest) => QuerySigningInfoResponse;
        SigningInfos: (r:QuerySigningInfosRequest) => QuerySigningInfosResponse;
    }
}

