// Code generated by protoc-gen-tstypes. DO NOT EDIT.

declare namespace cosmos.upgrade.v1beta1 {

    // QueryCurrentPlanRequest is the request type for the Query/CurrentPlan RPC
    // method.
    export interface QueryCurrentPlanRequest {
    }

    // QueryCurrentPlanResponse is the response type for the Query/CurrentPlan RPC
    // method.
    export interface QueryCurrentPlanResponse {
        // plan is the current upgrade plan.
        plan?: Plan;
    }

    // QueryCurrentPlanRequest is the request type for the Query/AppliedPlan RPC
    // method.
    export interface QueryAppliedPlanRequest {
        // name is the name of the applied plan to query for.
        name?: string;
    }

    // QueryAppliedPlanResponse is the response type for the Query/AppliedPlan RPC
    // method.
    export interface QueryAppliedPlanResponse {
        // height is the block height at which the plan was applied.
        height?: number;
    }

    // QueryUpgradedConsensusStateRequest is the request type for the Query/UpgradedConsensusState
    // RPC method.
    export interface QueryUpgradedConsensusStateRequest {
        // last height of the current chain must be sent in request
        // as this is the height under which next consensus state is stored
        last_height?: number;
    }

    // QueryUpgradedConsensusStateResponse is the response type for the Query/UpgradedConsensusState
    // RPC method.
    export interface QueryUpgradedConsensusStateResponse {
        // Since: cosmos-sdk 0.43
        upgraded_consensus_state?: Uint8Array;
    }

    // QueryModuleVersionsRequest is the request type for the Query/ModuleVersions
    // RPC method.
    //
    // Since: cosmos-sdk 0.43
    export interface QueryModuleVersionsRequest {
        // module_name is a field to query a specific module
        // consensus version from state. Leaving this empty will
        // fetch the full list of module versions from state
        module_name?: string;
    }

    // QueryModuleVersionsResponse is the response type for the Query/ModuleVersions
    // RPC method.
    //
    // Since: cosmos-sdk 0.43
    export interface QueryModuleVersionsResponse {
        // module_versions is a list of module names with their consensus versions.
        module_versions?: Array<ModuleVersion>;
    }

    // QueryAuthorityRequest is the request type for Query/Authority
    //
    // Since: cosmos-sdk 0.46
    export interface QueryAuthorityRequest {
    }

    // QueryAuthorityResponse is the response type for Query/Authority
    //
    // Since: cosmos-sdk 0.46
    export interface QueryAuthorityResponse {
        address?: string;
    }

    export interface QueryService {
        CurrentPlan: (r:QueryCurrentPlanRequest) => QueryCurrentPlanResponse;
        AppliedPlan: (r:QueryAppliedPlanRequest) => QueryAppliedPlanResponse;
        UpgradedConsensusState: (r:QueryUpgradedConsensusStateRequest) => QueryUpgradedConsensusStateResponse;
        ModuleVersions: (r:QueryModuleVersionsRequest) => QueryModuleVersionsResponse;
        Authority: (r:QueryAuthorityRequest) => QueryAuthorityResponse;
    }
}

